apiVersion: v1
kind: Namespace
metadata:
  name: ai-code-review

---
#api-keys-sealedsecret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: ai-code-review
spec:
  encryptedData:
    GOOGLE_APPLICATION_CREDENTIALS: AgCEI/eXEPctWcYE+NB2lUsBspIVUnnl1z+knCeULY9IqJg9Xu3+wgNzebFSJXV4YB4AbzLquOCTVfXZBzqaE/3qxJOy7xQaVaG2tS8aT8Qmkh4K+tCNoRBj/Bmq7kW4Slb21ngOr3geKLQ8y0CK58SqSc0b33rsyOK1qDkUMWlIXqrPMVSeT0/4RUEv7aD2FRtGk8QK9KC/YdOws/CKBbLp+q+xhBrdmR16Ay75qI8NtowQNiG5Zxqd1V1HOufExb85oT8oTowvt/0CePBONuA4waIZgPIMFus+GRTPtSxShKnZvHmcQ2vQWfu/Hy9EPfZrEeLSu5yBYRiWb20z4mpqd8RwYq2paKDQ2ay56SRNkGTpQswbanWGehNgee3+LAFsBj5m2U8qAd+5qaee26HDbGQ5JxKMf99I81+C0SfZv8vQ67Ml9gL5xN3STI/+QqAlJfX0vtfBzmXsHapmy6T1LDXEZJGzLpW4+HImML0+PiBgBCBgNoeIGbapqCCokv5CaxQ+JxnJwONq+vKUzsy4k/DzYmpJuz5YuaxZq7aYC86eU9XTDwZqYUjFBBdt97+db1rCVDMkMb5srJpoz8rEPoSmCBP8cywI8wgu/KHEUGwwY5O0JBWuUm5KDwfOzYzcRWmnApmE7PnIMVzH/WL82fYvJHKR9v5VzrduZuVWrQs1tY72/iGbuF4dS+AlhzJBVS0nMejzUI2e9nCFP/okYeIYo3MddOOhX3iarTDvV3MRcMU5Hvkv
    OPENAI_API_KEY: AgA2Qnl94XeS01GgBgQCDpqMojXI9HJEyDdclTjc80jPR0C6ylI4oO6haLUqrR21+JUXqU61Lak6O7oq9Ustli+0Jr6s1VvhYu/u9buhWCGS3aLKFfrKbcsBdr4coBrxwv9PkBZYA6anOfztvGqvqUSo0VQaCBRYK97t6W+0URkYVb03ZtUxZmoyP5Fe+Qv/Ay0/z7Il4+9retv/ypEtOOft2kvIt626aow5wI1slVuDntI0BYIo27c+zu0BoIxU00+sSEzE0EV9BM8z18z5oR8wECO7IJmWFcrlWs56JOjF3MvZtvs0phJJhGWzVLkXvPxAb1xaKHaUh+NcPD3GHsqA12rudP4lJjmxXsuRXkY71sJW4touOF+IyiiaaGJ433kZq4dRKJIlWRf00cCB43LKhXdgybMMYkWB7FS+gqFU0OMCnqGVmoFfW2r29xl82GEsvHIbHxhbQJgDns/8OXXpPWbqnmYreDLy7hE4RUtHy73hxwhxMzU2lqN7lkljeIcY9Eb61WnH4h7MkzVaIsC24bEcPoAGoQWvOs024CBl+nbyCvngh1jxaK36DWaWijTORZoGQgJPY65CWc5h5jv5sdW31MVJIn6i2IlTT6jd8FnDiGCfPO+IJc0LA6khnBEIplXlUJlrEnUrkGl1aIjp+mybcRGhykiSs3s4lL8nEsIG9lE53jnyKIBvaUGtUp2l/k9QblfH501qKbvEifet33dZxbcKWYol22SUkSFefVL4oAQ2Ti5aWSH++ApPMMoQRMYiF2cBgJMnP+qQUY/hyH4oD1sB2y2yIr9c780VuimtcM6NXKD0P6SyMq89rNVHH0c7coAKBH4m4iV5bGGZHDV0f+aIvvrgvgrhEVIDoMoDanGiUfIWnqil7fe3MofqFc0Jh3cRVmhpuaK5J/3QSxsLdg==
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: ai-code-review
    type: Opaque
   

---
#google-credentials-sealedsecret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: google-credentials
  namespace: ai-code-review
spec:
  encryptedData:
    google-credentials.json: AgC/gCZfAi7ywSmK33UQ23auZVUz2cjrppcucBE1flZMhSD5sjEbljGK/cVAgMlZ74PzZ78Y8R2h3IH9XLvRfB2S1H/XwHm7+5ldnRxPLiJG2UAMMf3hufu4ZjUMFVrdbA2BulZ1Wr6pmHVtC4jdVUEpGFqpzl4ya2cAWhRfzrZDk+dI8XOEi3DwVf7hjuL1O6s2MzbhtmhCd1SrHOM16HzabznHqGW2qdI1iZcfIM+aIOPhWVlxN8QtBoex28JCKyOeM9k423xUSaQt3smzjELkRvndwB9Sze+yDkbV1oF6iBScuuWyFkL1YtiGbhkZHQQW6b/HJ5hZH0eegSwTAWHJk2/Y6seC/XV37zSVfIKL/EoKFrMJpWoqawcTlwMfiJpaJtvLetDk3JPGrq49e0UCPb/SwaKQncxt6EaLDaxRdLUNBsQgYd/mALbWkE0htvoIlbBFVMMrNFoQIY0Ui13Ls3jH5ARGzsyEo0PD2IgqYLX1xFbB68oytoti3yqJOZilZs1Nng9FNKPcG0ejsXQDbL2YtXjXybe5wdev9J+i8Pm76wONofMlXy3PhjgT1u4w0CVpHyAZUiT4Z3aq6Fk2pD5W0WsKWOxjz3rFUifrNQ0n4cXQH5P5Cgm/TqNg8GuveIqaQfOUzT1vht5f6Vibsh63eYIQiHZbtWRjhS5xxhq7A8tU4PtGVCj2mWJFSX4Pa40GbbvTjaWoLQKaRfOzcVdiSDVi+EAMR5GubSYbmSZec9OeEvNypOmV/xTe2fW/nZ2SZrB23XqodWmX4sRNSk9P2e6GegGw1F5u7MG4nFEB2nk7JXIWYUeeJwn+7scLGeCZ4QMWSfQFN4xhtfHp72b6XCNB7q4FA5ppdzcKg0DYVi7/guI5KFRVXZVMvY2jgu4FFhNkJbooAa+6c8f2P1mEH1J8/5bRfiGRjEczNMDN12x9uyKDJtebDZCz9KBgcMGVT/nPxlAzuTY63PID2yTYBVT0svi/B5PA69nYP2W4+ipURf0oyZudi9MXF0sX/itx/VVhGtrTDSobTUQ9IKmjIzdU1lsIKmJ/xbSWvhXjW9IdkSB7bBbChH5Uf5WLILf1L4UxQMCAGMovQsmz+aqe1s8n9s4aKKFhCBuEy5PSb2BeCaxdBqLYcRh3wcSeWP5e6pIjxXYaMgP3rcb6NFILzWCuN5G7Y3bpuHPMMKzpirzQR/jZftv5X274PYXnq+VFUGNAhrji8M/c9abXl5gtLI8zl6BXnPaPLr90s58MtIVF/8tMzawgBQgpzzNILwMYgnjQhdKQv22vZ2OQb0tQyCpwnY6XrtmiFZTBNpKeBgxQMN6ijpyqCaB+OwVAErHPBEVRpKbgaLpmmnU0GyEKVK1Je32oNnJK4cSF5EcNKFkMPrn/P7rQBk/Qn8+b+OVuPHa4uK5xmI9s3Wq7QVHoRghhc1vnqIvr7hkv/bcTx+IlhD0nMafD6GV6q13U0UBdBbnofm4g1jlANTT2DgW84EKXlCf3l5sw7yzRuoRNiZOtk8lb8XEMRs6XM7KGher5tN27hMQoPBG4DzUJqu9SOOdegqkJJcwD+vN4nF+7z7W8arHUNLm+QtUGNsUKsBSTzPjWYBwth1Mo0eJTQjNhO545DklN8xW2AgRoe8fQB3uh09BkL1K5cM+DwAno8VFXV+I6fxYGAVEGsb3mqsOhSm2KmOwomOLTfEIzL2NIOJhBNGzzdPSbCPAFklDSjr1BXvuo9HQ0el3kEF+tHLzUTFA+NerbzzO3rgUrd30qFkZdYeMoCmlGRNwExEjtyI9R8sfB6NzrgyQaYZJyqTFDeRNbzjubVFkqlX6RTjSWZLynIbTMQKSTo0kYwLDjDJr1WEM20Bm3DJ7RQk/T6XyIDkbgSPeNBH6rXBY3+14B5kMkrRF+zQ9KSgbCV7Ob/Ziu+gN6iGCvmtCdr0uzU4w+ltpBPxb2KpjjeczSH7ZUmC/5pjiyRBNH/JiJGNk8ZuvN2xcEPzBvzZSmCsDyL7BWGECtV6AD2tCFsh7isyP6xSVA9wLCYqK08ZMuoGpBztmkWDRmWz028+PBh5+30ZLO16eLo4P2IR7SBjTy7FWHNOywlKz9IhNM4i+U3w77Ma47RZdpN70Y98rZH82KK7jPUOjJK/5/+ybP/TZEOwWgAIXEA9YrZhH2VfUZt3y0tfgYlWQWj7j5XOlWNjZuZ2nfB3HvbYugD6GVUxLIuY5JTEOFbAdJcxqXQJiNkHcOHhtanvq3r41ASa7/pXBan+GtkeB35R82E1cPxVo0u45A1Fn+KgRlr3275HoFY6Rlr2V5AmD2YwlPzRciTe+1iWFR5ZjlloFOZ1v4VCqPhyFYHBWhInffMSH0K5f4q2ABpsFgaa3fAyT4BkEpTEABztZRpgS9B7wEG0/sBEbnc0URAgHP9nCNUf66ZalaAJF503YvMAweuXRUuFSwZygNXCwIHxJ2g1Ae1rA4x214FkR6OppZBN509ZCrLd/amdC0p6b9DQ4HWa0Dxwl2frveXM4SEEZCUwZgjeCfEeQMpxdZt7CmZzDT8xOTHS70GO+qascTJvKcZ+FFNlH2GnIo4KTSwSKTr2HMeKBOvfVO1QuDo7sEAhVvmTndZAKYCWtNlxOXsFE53g8y6sTFZkxPqnXkTxg2SYU7DnDEeOrqq1HpQMxMlU0OM3w7L0wGqYDd7a0XwNI85kEIaaIHikacQDPbRoeUyPk354lCm+7NT5ZWnWI78SSbGy5ZnGam6g6MuJLKj/flkVutAa26aIe0nFaqZhvsXVWTmSVHW5FZ5Jhv64e98UFv55qj2hmjWlcce/KnkAEfCBHIcmClbRaTkgs+WRHLt91gODV+KAc7qfyT9556SRBwjL8n5vRKIL+HZTGUtcz8uzBswjcJ57JawpAcidn9aUTHnrJ4OiOimLibtOdhm8lDqYj93agO04/Mz7VOmk9l4PgX/QoUKM8i5GTaiLvWgKXgmofvi0zrknYtYL+HsQYFdOSEhyxz4mjpATIa0kejCss1RLHZ12PJqV9K6BoQOgPwzZvhclcw04U9/vo6PT95k0zWSSHP4GogNobqr8sGUMZCirLoQCK84Edf2YQxMRdYP+TZsS1gVC3iny+39Psgxdbky1R/WEIpZo2cewV634hRyI/ui91Fa0FNckUltUf6E5TuB6/ajNlHOD2oueGX+H6G0kCNjAJD20v5PtQUVHtJS8Tb04b2QGWZH9z4z61BWa5eDObz22Vy5rsgpAPfR9dQtzne/cWuStVHxGdKgUiyyMlhWVqWHp5bzBoGYOaXsIEh1wp3g5K8fTwxOj7tnZlOYfBmrgWzOIvlBKTlX9UBRFOg41bXepTbToiNlARgOC0Wz0bfpiHrjz3zTu6vOawqbBeywRiQFaNVc8IE261P0vLr/3kNGY3TC3/PnRD+Zj955+za1AA+lIxQhllyV91BrhIloyq1wvvyzRL7nf8zMb6ng2klWwMk2fCRoIsJfWn9uuEgUeOHTx/pWFD8NGNBLhQIx+35GfpjvDu7u8Z1a+FA5gUB6Q4AguVzsQ+H4HnNybqPgltWwMAh/I1f8tKcbip5zy2qqnUrkFbhZdJzR1c0CL/3z7zSnGakh87WJG7pJwIqgsJQnDWzT/bUZR155ofHsMtNmno4s2+qj8FDkstGGp3jU0nG40ebBBbZymb3loBLwef407HgK/3yGQjl2cXTGB3fdvgCyihoY5s8vc5HK5DZ4Bm/GhotxY5sdN60bX6yXVXsHn+vcxrgGkgR0mrU+eLlF9SNzDvAiakaCUNWlCGTt6qoUDJo071MC3hugSTP3rIR5e7lhg==
  template:
    metadata:
      creationTimestamp: null
      name: google-credentials
      namespace: ai-code-review
    type: Opaque
---

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-storage
  namespace: ai-code-review
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: ai-code-review
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: us-central1-docker.pkg.dev/ai-bugger/ai-code-review-platform/backend:v1.1
        ports:
        - containerPort: 8000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: OPENAI_API_KEY
        - name: GOOGLE_APPLICATION_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: GOOGLE_APPLICATION_CREDENTIALS
        - name: PYTHONPATH
          value: "/app"
        volumeMounts:
        - name: storage
          mountPath: /app/logs
        - name: google-creds
          mountPath: /app/credentials
          readOnly: true
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: backend-storage
      - name: google-creds
        secret:
          secretName: google-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ai-code-review
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: ai-code-review
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: us-central1-docker.pkg.dev/ai-bugger/ai-code-review-platform/frontend:v1.0
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ai-code-review
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-code-review-ingress
  namespace: ai-code-review
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "ai-code-review-ip"
spec:
  rules:
  - host: your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80